Add pylint to github action.

diff --git a/.github/workflows/quality-checks.yaml b/.github/workflows/quality-checks.yaml
--- a/.github/workflows/quality-checks.yaml
+++ b/.github/workflows/quality-checks.yaml
@@ -18,17 +18,47 @@ jobs:
       - name: Set up Python
         run: uv python install
 
+      - name: Install the project
+        run: uv sync --all-extras --dev
+
+      - name: Generate requirements.txt
+        run: uv pip compile pyproject.toml -o requirements.txt
+
       - name: Install Tesseract OCR
         run: |
           sudo apt-get update
           sudo apt-get install -y tesseract-ocr
           tesseract --version
 
-      - name: Install the project
-        run: uv sync --all-extras --dev
-
       - name: Run ruff
         run: uv run ruff check .
+
+      - name: Run Pylint
+        run: uv run pylint \
+          --disable=C0114,C0115,C0116,R0903,C0415,E1101,E1102,R0917,R0913,C0103,R0901,C0411 \
+          --exit-zero \
+          --output-format=text:pylint.txt,colorized \
+          app/**/*.py tests/**/*.py
+
+      - name: Validate Pylint score
+        run: |
+          # Read pylint.txt and extract the rating using regex
+          $pylintOutput = Get-Content "./pylint.txt" -Raw
+          $match = $pylintOutput -match "Your code has been rated at ([\d\.]+)/10"
+          if (!$match) {
+            Write-Error "Could not find Pylint score in the output."
+            exit 1
+          }
+          $score = [float]$matches[1]
+          Write-Host "Pylint score extracted: $score"
+          # Fail the step if the score is less than 9
+          if ($score -lt 9) {
+            Write-Error "Pylint score is below the threshold of 9!"
+            exit 1
+          } else {
+            Write-Host "Pylint score is acceptable."
+          }
+        shell: pwsh
 
       - name: Type check main app
         run: uv run mypy -p app --strict --ignore-missing-imports
